"""
GenAR Version 0 — report generation orchestrator.

Pipeline:
    raw data -> analysis.py (deterministic) -> per-section evidence packets
    -> LLM (one call per section, minimal scoped context) -> draft sections
    -> human review gate (approve/flag, stored in review_state.json)
    -> approved sections assembled into report_output.md

Run:
    python src/generate_report.py <path-to-data.xlsx-or-csv> [--offline]

--offline skips the Anthropic API call and instead renders each section from
a template using only the packet numbers (still 100% grounded, just no LLM
prose). Useful for demoing the pipeline without an API key.
"""
import argparse
import json
import os
import sys
from datetime import datetime

sys.path.insert(0, os.path.dirname(__file__))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "prompts"))

from analysis import load_data, run_analysis
import sections as section_defs


def call_llm(system_prompt: str, packet: dict, instructions: str) -> str:
    """Single call to Claude for one section. Requires ANTHROPIC_API_KEY."""
    import anthropic
    client = anthropic.Anthropic()
    user_msg = (
        f"Section instructions: {instructions}\n\n"
        f"Evidence packet (JSON — the ONLY facts you may use):\n"
        f"{json.dumps(packet, indent=2, default=str)}"
    )
    resp = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=600,
        system=system_prompt,
        messages=[{"role": "user", "content": user_msg}],
    )
    return "".join(b.text for b in resp.content if b.type == "text")


def render_offline(packet: dict, section_name: str) -> str:
    """Deterministic, non-LLM fallback: turns the packet into flat prose.
    Zero interpretation — literally lists the numbers. Proves the pipeline
    runs end-to-end without requiring API access."""
    lines = [f"[Offline mode — no LLM call made. Raw evidence for '{section_name}':]"]
    lines.append(json.dumps(packet, indent=2, default=str))
    return "\n".join(lines)


def build_sections(analysis: dict, offline: bool) -> list[dict]:
    system_prompt = open(
        os.path.join(os.path.dirname(__file__), "..", "prompts", "system.txt")
    ).read()

    drafts = []
    for name, packet_fn, instructions in section_defs.SECTIONS:
        packet = packet_fn(analysis)
        if offline:
            text = render_offline(packet, name)
        else:
            try:
                text = call_llm(system_prompt, packet, instructions)
            except Exception as e:
                text = f"[LLM call failed: {e}. Falling back to raw evidence.]\n" + render_offline(packet, name)
        drafts.append({
            "section": name,
            "packet": packet,
            "text": text,
            "review_status": "pending",  # human review gate — see review_state.json
        })
    return drafts


def render_case_index(analysis: dict) -> str:
    rows = analysis["case_index_sample"]
    header = "| Case ID | Reaction | Serious | Received | Country | Outcome |\n"
    header += "|---|---|---|---|---|---|\n"
    body = ""
    for r in rows:
        body += (
            f"| {r.get('safetyreportid','')} | {r.get('patient_reaction_reactionmeddrapt','')} "
            f"| {r.get('serious','')} | {r.get('receivedate','')} | {r.get('occurcountry','')} "
            f"| {r.get('patient_reaction_reactionoutcome','')} |\n"
        )
    note = (f"\n*Showing 20 of {analysis['case_index_full_count']} cases. "
            f"Full listing available in the underlying dataset / case_index export.*\n")
    return header + body + note


def assemble_report(analysis: dict, drafts: list[dict]) -> str:
    md = []
    md.append("# Periodic Adverse Drug Experience Report (PADER-style)\n")
    md.append("**Product:** Bisoprolol  \n")
    md.append(f"**Reporting period:** {analysis['reporting_period']['start']} to {analysis['reporting_period']['end']}  \n")
    md.append(f"**Report generated:** {datetime.utcnow().date().isoformat()} (Version 0 prototype)  \n")
    md.append(f"**Data note:** {analysis['meta']['dedup_note']}. {analysis['meta']['country_field_used']}.\n")

    for d in drafts:
        md.append(f"\n## {d['section']}\n")
        md.append(d["text"].strip() + "\n")

    md.append("\n## Case Index / Listing (sample)\n")
    md.append(render_case_index(analysis))

    md.append(
        "\n---\n*Generated by a prototype system for the GenAR AI Engineering "
        "Challenge. Not a real regulatory submission. All figures traced to "
        "src/analysis.py output — see review_state.json for the human "
        "approval status of each section.*\n"
    )
    return "\n".join(md)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("data_path")
    ap.add_argument("--offline", action="store_true")
    ap.add_argument("--out", default="report_output.md")
    args = ap.parse_args()

    df = load_data(args.data_path)
    analysis = run_analysis(df)

    with open("analysis_output.json", "w") as f:
        json.dump(analysis, f, indent=2, default=str)

    drafts = build_sections(analysis, offline=args.offline)

    # Human review gate: every section starts "pending". A reviewer edits
    # this file (or a UI backed by it) to set "approved" or "flagged" per
    # section before the report is treated as final. See README for how
    # this would become a real UI.
    with open("review_state.json", "w") as f:
        json.dump(
            [{"section": d["section"], "review_status": d["review_status"]} for d in drafts],
            f, indent=2,
        )

    report = assemble_report(analysis, drafts)
    with open(args.out, "w") as f:
        f.write(report)

    print(f"Wrote {args.out}, analysis_output.json, review_state.json")


if __name__ == "__main__":
    main()
